[package]
name = "iced_swviewer"
version = "0.1.0"
edition = "2024"
default-run = "iced_swviewer"

[[bin]]
name = "cli_parser"

[dependencies]
fixed = "1.29.0"
heapless = "0.9.2"
iced = "0.14.0"
iced_futures = "0.14.0"
iced_plot = "0.1.0"
thiserror = "2.0.17"
