[package]
name = "iced_swviewer"
version = "0.1.0"
edition = "2024"

[dependencies]
fixed = "1.29.0"
foxglove = "0.16.2"
heapless = "0.9.2"
prost = "0.13.5"
prost-types = "0.13.5"
thiserror = "2.0.17"
